CREATE TABLE public.items (
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	product_code varchar(255) NOT NULL,
	quantity float8 NOT NULL,
	amount float8 NOT NULL,
	unit_measure varchar(255) NULL,
	item_type varchar(255) NULL,
	item_type_id int4 NULL,
	description varchar(255) NOT NULL,
	cfop int4 NOT NULL,
	bc_icms_amount float8 NOT NULL,
	brute_total_value float8 NOT NULL,
	icms_aliquot float8 NOT NULL,
	icms_amount float8 NOT NULL,
	bc_icms_st_amount float8 NOT NULL,
	st_aliquot float8 NOT NULL,
	icms_st_amount float8 NOT NULL,
	item_sequential_number int4 NOT NULL,
	cest int4 NULL,
	barcode varchar(255) NULL,
	framing_code varchar(255) NOT NULL,
	situation int4 NOT NULL,
	tax_situation varchar(2) NOT NULL
);